### ISSUE TITLE
PLoPで得たフィードバックを反映する

### ISSUE THREAD

**Issue by irohiroki** [rails-patterns/rails_dev_patterns#23]
- [x] 図を直す
    - [x] **レール圏**を最初に
    - [x] パターンの重なり合いはもっと曖昧なはず
    - [x] 適用の順番が分かるように
    - [x] 名前の更新を反映する
- [ ] はじめにを直す
    - [ ] パターンの対象者と使い方を追記する。なぜこのパターン・ランゲージがあると良いのか。Railsの落とし穴を簡単に
    - [ ] パターンの抽出方法や、紹介してないパターンのこと、紹介しているパターンがどうやって選ばれたか
- [ ] **レール圏**を直す
    - [ ] 名前
    - [ ] 最初に適用するパターンとして書き直し
- [x] **公式情報**を直す
    - [x] 解決方法の「Railsの機能について調べるとき」は状況へ移動
    - [x] 解決方法の適用例かと思って読み始めると問題が書かれていて違和感がある
    - [x] 第三者による発信の正しい使い方にも言及する。日付やバージョンをチェックするとか
    - 結果の「完全な」という表現は危険 → ソースコードは本当に完全な情報なのでそのままにする
- [x] **Rails Way**を直す
    - [x] 名前を造語に
    - [x] 解決方法の「Rails Wayがないか確認し」は飛びすぎ
- [x] **レスポンシブテスト**を直す
    - [x] 名前
    - [x] 解決方法に「開発の初期から」と書かれているので、状況も初期でなければならない
- [x] **コードの節制**を直す
    - [x] 名前
- [ ] まとめを直す。はじめにと同じことを書いても価値はない
- [ ] 「適切」という表現では不十分。何が適切か分かるように

**Comment by ukstudio** [comment]
:+1:  今ちょっと本業で手一杯なんですが、4月中旬ぐらいからならまたお手伝いできるかもしれません！

**Comment by irohiroki** [comment]
おお！お願いします！

**Comment by irohiroki** [comment]
「レール圏」は完成度が低かったので一度リストから外す。このissueではパターンの修正のみを扱う。（論文としての修正は本issueのスコープ外。）

これで5パターンがMarkdown化されたが、他のパターンの種を検討して語彙を増やしていく。（もちろん5パターンのブラッシュアップもする。）
